services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    restart: unless-stopped
    volumes:
      - ./backend/src:/app/src:ro
      - ./backend/package.json:/app/package.json:ro
      - ./backend/package-lock.json:/app/package-lock.json:ro
      - ./backend/tsconfig.json:/app/tsconfig.json:ro
    environment:
      - NODE_ENV=development
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-1h}
      - PORT=3001
      - FRONTEND_URL=http://localhost:3000
    networks:
      - app-network
    labels:
      - "com.example.description=Events Site Backend API (Dev)"
      - "com.example.version=1.0"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./src:/app/src
      - ./public:/app/public:ro
      - ./package.json:/app/package.json:ro
      - ./package-lock.json:/app/package-lock.json:ro
      - ./tsconfig.json:/app/tsconfig.json:ro
      - ./tsconfig.node.json:/app/tsconfig.node.json:ro
      - ./vite.config.ts:/app/vite.config.ts:ro
      - ./index.html:/app/index.html:ro
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:3001/api
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-network
    depends_on:
      - backend
    labels:
      - "com.example.description=Events Site Frontend (Dev)"
      - "com.example.version=1.0"

networks:
  app-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: events-bridge