services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - '3001:3001'
        restart: unless-stopped
        security_opt:
            - no-new-privileges:true
        cap_drop:
            - ALL
        cap_add:
            - CHOWN
            - SETGID
            - SETUID
        read_only: true
        tmpfs:
            - /tmp:rw,noexec,nosuid,size=50m
        healthcheck:
            test:
                [
                    'CMD',
                    'wget',
                    '--no-verbose',
                    '--tries=1',
                    '--spider',
                    'http://localhost:3001/health',
                ]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s
        environment:
            - NODE_ENV=production
            - JWT_SECRET=${JWT_SECRET}
            - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-1h}
            - PORT=3001
            - FRONTEND_URL=http://localhost:3000
        networks:
            - app-network
        labels:
            - 'com.example.description=Events Site Backend API'
            - 'com.example.version=1.0'

    frontend:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3000:8080'
        restart: unless-stopped
        security_opt:
            - no-new-privileges:true
        cap_drop:
            - ALL
        cap_add:
            - CHOWN
            - DAC_OVERRIDE
            - SETGID
            - SETUID
        read_only: true
        tmpfs:
            - /var/cache/nginx:rw,noexec,nosuid,size=50m,uid=101,gid=101
            - /var/run:rw,noexec,nosuid,size=50m,uid=101,gid=101
            - /tmp:rw,noexec,nosuid,size=50m
        healthcheck:
            test:
                [
                    'CMD',
                    'wget',
                    '--no-verbose',
                    '--tries=1',
                    '--spider',
                    'http://localhost:8080/health',
                ]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s
        environment:
            - NODE_ENV=production
            - REACT_APP_API_URL=http://localhost:3001/api
        networks:
            - app-network
        depends_on:
            backend:
                condition: service_healthy
        labels:
            - 'com.example.description=Events Site Frontend'
            - 'com.example.version=1.0'

networks:
    app-network:
        driver: bridge
        driver_opts:
            com.docker.network.bridge.name: events-bridge
